### ISSUE TITLE
Python 3.8: platform.linux_distribution() deprecated

### ISSUE THREAD

**Issue by rubenvdham** [GNS3/gns3-gui#2973]
**GNS3 version and operating system (please complete the following information):**
 - OS: Manjaro Linux, python 3.8.2
 - GNS3 version AUR gns3-gui-git-v2.1.9.r25.g3000a9aa-1

```Fail update installation: module 'platform' has no attribute 'linux_distribution'
Traceback (most recent call last):
  File "/usr/bin/gns3", line 11, in <module>
    load_entry_point('gns3-gui===2.1.22dev1-e2aeaf0a', 'gui_scripts', 'gns3')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/gns3/main.py", line 55, in <module>
    from gns3.main_window import MainWindow
  File "/usr/lib/python3.8/site-packages/gns3/main_window.py", line 27, in <module>
    from .local_config import LocalConfig
  File "/usr/lib/python3.8/site-packages/gns3/local_config.py", line 29, in <module>
    from .controller import Controller
  File "/usr/lib/python3.8/site-packages/gns3/controller.py", line 25, in <module>
    from .settings import LOCAL_SERVER_SETTINGS
  File "/usr/lib/python3.8/site-packages/gns3/settings.py", line 164, in <module>
    distro = platform.linux_distribution()[0]
AttributeError: module 'platform' has no attribute 'linux_distribution'
```

**To Reproduce**
Run `gns3`

**Issue:**
Function deprecated in [Python 3.8](https://docs.python.org/3.8/library/platform.html)

**Comment by grossmj** [comment]
GNS3 version 2.2 should work with Python 3.8

**Comment by cioby23** [comment]
I'm using also GNS3 on ArchLinux (Manjaro is a fork of Archlinux) on it works fine.

@rubenvdham This package gns3-gui-git **https://aur.archlinux.org/packages/gns3-gui-git/** is outdated and it based on 2.1 git branch. You should use this one h**ttps://aur.archlinux.org/packages/gns3-gui/** which is up-to-date and also **https://aur.archlinux.org/packages/gns3-server/**

@grossmj From my opinion this issue can be closed.

**Comment by grossmj** [comment]
@cioby23 thanks for the feedback :+1:
