### ISSUE TITLE
GNS3 VM integration issue after upgrade to 2.0 Alpha from 1.5.3

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-gui#1588]
After upgrading to 2.0 Alpha from 1.5.3, I experience several issues. Firstly, I observe the following two errors below upon starting. Secondly, GNS3 VM does not start on GNS3 load, and the GNS3 VM settings cannot be applied, any changes made are lost upon opening preferences. And when I tried to save the debug information zip for this bug report, I got the following error below. I'm including files in the roaming traceback directory the error points to.

```
=> Could not bind with 192.168.6.1: [WinError 10049] The requested address is not valid in its context (please check your host binding setting in the preferences)
Could not start the local server process: C:\Program Files\GNS3\gns3server.EXE
```

![image](https://cloud.githubusercontent.com/assets/6335629/19541473/92358190-9634-11e6-8bd6-d22c51fdaa1f.png)

![image](https://cloud.githubusercontent.com/assets/6335629/19541485/a7f8ce06-9634-11e6-8917-169bc81414a2.png)

```
PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "./gns3-gui\gns3\dialogs\export_debug_dialog.py", line 64, in _okButtonClickedSlot
AttributeError: 'NoneType' object has no attribute 'filesDir'

****** Exception detected, traceback information saved in C:\Users\Ariel\AppData\Roaming\GNS3\exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "./gns3-gui\gns3\dialogs\export_debug_dialog.py", line 64, in _okButtonClickedSlot
AttributeError: 'NoneType' object has no attribute 'filesDir'
```

Windows 7 64 bit SP1
VMWare Workstation 12.5.0
GNS3 2.0.0A1
GNS3 VM 2.0.0 Release channel 2.0

**Comment by codeassassin** [comment]
There seems to be an issue uploading the files. Despite ZIP files supposedly being supported, when I try to add the file, git errors with, "we don't support that file type". I can convert the files to txt if you need them, let me know.

**Comment by noplay** [comment]
For the start please follow this discussion #1589

The export is fixed in dev version. I will put a link in #1589 for downloading the dev release in order to tests.

**Comment by AJNOURI** [comment]
Looks like the issue persists in v2.1.2. Maybe another root cause:

-----------------

From community forum:
https://gns3.com/qa/error-when-connecting-to-the-g-3

![image](https://user-images.githubusercontent.com/1716020/34921602-1ea5a1aa-f985-11e7-927a-08152c848931.png)


 
Error while getting compute list: Connection refused
Error while getting settings : Cannot connect to http://192.168.2.1:3080. Please check if GNS3 is allowed in your antivirus and firewall. And that server version is 2.1.1.
 
 
Show error when gns3 vm starts
 
GNS3 management console.
Running GNS3 version 2.1.1 on Windows (64-bit) with Python 3.6.3 Qt 5.8.0 and PyQt 5.8.
Copyright (c) 2006-2018 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.
 => Could not bind with 192.168.10.1: [WinError 10049] The requested address is not valid in its context (please check your host binding setting in the preferences)
Could not start the local server process: C:\Program Files\GNS3\gns3server.exe
Local server process has stopped
C:\Program Files\GNS3\lib\raven\conf\remote.py:90: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
 
Error while getting compute list: Connection refused
 

![image](https://user-images.githubusercontent.com/1716020/34921611-4969f10c-f985-11e7-8e78-1d2d3abb3485.png)

 
Error while getting compute list: Connection refused
Error while getting settings : Cannot connect to http://192.168.2.1:3080. Please check if GNS3 is allowed in your antivirus and firewall. And that server version is 2.1.1.

![image](https://user-images.githubusercontent.com/1716020/34921614-524b5c66-f985-11e7-971f-0f1722eddf05.png)

**Comment by Karlheinzniebuhr** [comment]
Same issue
