### ISSUE TITLE
Style manipulation doesn't work at GNS3 3.0.6

### ISSUE THREAD

**Issue by ivanovuri** [GNS3/gns3-gui#3831]
Please note that the issue for GNS3 3.0.6 version.

**Describe the bug**
This is the full output from GNS3 console. It is said to send me a report. ;-)

=> ****** Exception detected, traceback information saved in C:\Users\Tikal\AppData\Roaming\GNS3\3.0\exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "C:\Users\circleci\project\Windows\gns3-gui\gns3\dialogs\style_editor_dialog_link.py", line 108, in _applyPreferencesSlot
  File "C:\Users\circleci\project\Windows\gns3-gui\gns3\items\link_item.py", line 154, in setLinkStyle
  File "C:\Users\circleci\project\Windows\gns3-gui\gns3\link.py", line 177, in update
  File "C:\Users\circleci\project\Windows\gns3-gui\gns3\controller.py", line 199, in put
  File "C:\Users\circleci\project\Windows\gns3-gui\gns3\controller.py", line 244, in request
  File "C:\Users\circleci\project\Windows\gns3-gui\gns3\http_client.py", line 354, in sendRequest
  File "C:\Users\circleci\project\Windows\gns3-gui\gns3\qt\__init__.py", line 182, in partial
  File "C:\Users\circleci\project\Windows\gns3-gui\gns3\http_client.py", line 728, in _executeHTTPQuery
  File "C:\Users\circleci\project\Windows\gns3-gui\gns3\http_client.py", line 378, in _addBodyToRequest
  File "C:\python311\Lib\json\__init__.py", line 231, in dumps
  File "C:\python311\Lib\json\encoder.py", line 200, in encode
  File "C:\python311\Lib\json\encoder.py", line 258, in iterencode
  File "C:\python311\Lib\json\encoder.py", line 180, in default
TypeError: Object of type PenStyle is not JSON serializable

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows client, Linux server
 - GNS3 3.0.6
 - Ubuntu 26.04 Bare metal

**To Reproduce**
1. Go to the link style editor
2. Click on border width
3. Press apply button and after that pressing on Ok doesn't close window only cancel button works. Ad the same time link style is changed.
5. After reopening project all customizations are lost.

**Screenshots or videos**
Video reproducing bug also included. Take a look please.

https://github.com/user-attachments/assets/8fce628b-adf3-45a1-9fc8-b0298ce84cea

**Comment by grossmj** [comment]
Thanks for reporting 👍  I think we have already fixed the issue though, it should work in v3.1 alpha 2

**Comment by ivanovuri** [comment]
> Thanks for reporting 👍 I think we have already fixed the issue though, it should work in v3.1 alpha 2

Thanks Jeremy.
Any chance to install latest alpha versions from ubuntu repository in near future?
Maybe it's good idea to make some unstable repository.

**Comment by grossmj** [comment]
> Any chance to install latest alpha versions from ubuntu repository in near future?
Maybe it's good idea to make some unstable repository.

I have created an unstable repository for v3: https://launchpad.net/~gns3/+archive/ubuntu/unstable-v3/

**Comment by ivanovuri** [comment]
> > Any chance to install latest alpha versions from ubuntu repository in near future?
> > Maybe it's good idea to make some unstable repository.
> 
> I have created an unstable repository for v3: https://launchpad.net/~gns3/+archive/ubuntu/unstable-v3/

Thanks Jeremy. I've installed latest version.
After upgrade GNS3 failed to start because of SQL DB
```
2026-06-03 06:52:10 INFO migration.py:621 Running upgrade  -> 7ceeddd9c9a8, init
2026-06-03 06:52:10 INFO migration.py:621 Running upgrade 7ceeddd9c9a8 -> 9a5292aa4389, add mac_address field in Docker templates table
2026-06-03 06:52:10 CRITICAL tasks.py:138 Error while connecting to database 'sqlite+aiosqlite:////etc/gns3/gns3_controller.db: (sqlite3.OperationalError) duplicate column name: mac_address
[SQL: ALTER TABLE docker_templates ADD COLUMN mac_address VARCHAR]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

After removing database with sudo `rm /etc/gns3/gns3_controller.db` GNS3 created new one on start and it works like a charm.

Link editing also works as expected in alpha 2 version.
