### ISSUE TITLE
Problem with gns3 - v2.1.3

### ISSUE THREAD

**Issue by patricklind** [GNS3/gns3-gui#2397]
After upgrading from 2.1.2 to 2.1.3, gns3 does not work.
I have tried to install gns3 on two different PCs with the same error

Error log 
GNS3 management console.
Running GNS3 version 2.1.3 on Windows (64-bit) with Python 3.6.3 Qt 5.8.0 and PyQt 5.8.
Copyright (c) 2006-2018 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> Local server process has stopped
Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "gns3-server/gns3server/main.py", line 87, in <module>
  File "gns3-server/gns3server/main.py", line 82, in main
  File "./gns3-server\gns3server\run.py", line 32, in <module>
  File "./gns3-server\gns3server\web\web_server.py", line 26, in <module>
  File "C:\Python36-x64\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
  File "C:\Python36-x64\lib\site-packages\aiohttp\client.py", line 13, in <module>
  File "C:\Python36-x64\lib\site-packages\yarl\__init__.py", line 8, in <module>
  File "C:\Python36-x64\lib\site-packages\idna\__init__.py", line 2, in <module>
  File "C:\Python36-x64\lib\site-ackages\idna\core.py", line 1, in <module>
ImportError: cannot import name 'idnadata'

**Comment by cioby23** [comment]
There is an already open bug for this issue. Check here https://github.com/GNS3/gns3-server/issues/1266

**Comment by anand20raj** [comment]
Recently formatted my machine, installed win 10 64bit, got the latest gns3 but getting the same error as above, any way-around to this error??

**Comment by grossmj** [comment]
Thanks for reporting. We are going to release a new version very soon.

**Comment by grossmj** [comment]
Decided to keep version 2.1.3 since the problem was due to a packaging problem. Please download & install again.
