### ISSUE TITLE
Project does not load anymore

### ISSUE THREAD

**Issue by IurmanJ** [GNS3/gns3-gui#3140]
**Describe the bug**
When opening a project locally, GNS3 does not load (or, at least, display) it anymore. No error, it just fails silently. This issue appeared after upgrading to 2.2.18 (I was on 2.2.17 before that, everything was working fine).

**GNS3 version and operating system:**
 - OS: Linux (Ubuntu 18.04.5 LTS)
 - GNS3 version: 2.2.18

**To Reproduce**
Either via "File > Open project" or by directly opening a project file. Same behavior (see screenshot).

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/23418985/109427211-993e2c80-79f1-11eb-9ce3-359b76a0145d.png)

**Comment by IurmanJ** [comment]
I forgot to mention that starting GNS3 alone works. I can see the gns3 server up and running and the GUI is asking for a project to create/open.

**Comment by IurmanJ** [comment]
@grossmj Any idea of the origin?

**Comment by grossmj** [comment]
> @grossmj Any idea of the origin?

No but you could try to manually start the GNS3 server and see if you have any message indicating an error.

Type this to start the server in a terminal: `python3 -m gns3server --local`

**Comment by IurmanJ** [comment]
Sure, glad to help. I actually got something quite interesting:

```
2021-03-02 13:02:20 ERROR web_protocol.py:355 Error handling request
Traceback (most recent call last):
  File "/usr/share/gns3/gns3-server/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
```

Same behavior for both the direct opening of a project or the opening of GNS3 alone.

**Comment by grossmj** [comment]
Interesting, have you tried to configure SSL with the server or client?

**Comment by IurmanJ** [comment]
No, I didn't. Should I?

**Comment by eknoes** [comment]
I have a similar problem: I start GNS3 with a project like that `gns3 PATH-TO-PROJECT` and it used to work. After upgrading from 2.2.7 to 2.2.19 it does not load at the first stage, but after clicking on "New Blank Project", the initial loaded project is displayed and everything works like normal.

Server output:
```
2021-04-05 10:35:00 INFO web_log.py:233 127.0.0.1 [05/Apr/2021:10:35:00 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.19"
2021-04-05 10:35:00 INFO web_log.py:233 127.0.0.1 [05/Apr/2021:10:35:00 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.19"
2021-04-05 10:35:00 INFO web_log.py:233 127.0.0.1 [05/Apr/2021:10:35:00 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.19"
2021-04-05 10:35:00 ERROR web_protocol.py:355 Error handling request
Traceback (most recent call last):
  File "/usr/share/gns3/gns3-server/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "/usr/share/gns3/gns3-server/lib/python3.8/site-packages/aiohttp/http_parser.py", line 264, in feed_data
    msg = self.parse_message(self._lines)
  File "/usr/share/gns3/gns3-server/lib/python3.8/site-packages/aiohttp/http_parser.py", line 437, in parse_message
    raise BadStatusLine(method)
aiohttp.http_exceptions.BadStatusLine: /version

# Here, only a blank screen is shown. After clicking "New Blank Project", the following happens:

2021-04-05 10:35:09 INFO web_log.py:233 127.0.0.1 [05/Apr/2021:10:35:09 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.19"
2021-04-05 10:35:09 INFO notification_handler.py:73 New client has connected to controller WebSocket                                                                                         
```

**Comment by b-ehlers** [comment]
This `aiohttp.http_exceptions.BadStatusLine: /version` error was also reported in https://github.com/GNS3/gns3-gui/issues/3144, in my case it didn't create any bad effects. But I have to confess I started gns3 without an argument.

**Comment by IurmanJ** [comment]
> [...] it does not load at the first stage, but after clicking on "New Blank Project", the initial loaded project is displayed and everything works like normal.

+1, got the same behavior. Btw, thx for the temp solution before a fix.

**Comment by eknoes** [comment]
I tried a quick fix for #3144 which resolves the wrong request error, but does not resolve the project loading error:

```
        status, json_data = self.httpClient().getSynchronous('GET', '/version', timeout=60)
        self._versionGetSlot(json_data, status >= 300)
```

But I do not know, if this is the intended way to use self._versionGetSlot

**Comment by grossmj** [comment]
Should be fixed now. Thanks.
