### ISSUE TITLE
Right click on any device the Servers Summary panel does not open the context menu (GNS3 3.0.0dev7)

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-gui#3508]
After adding an device and trying to right click on the device name in the Servers summary panel no context menu is being displayed.

Environment details:
OS: ArchLinux
GNS3 version: 3.0.0dev7
Python 3.11

1. Drag a new device on the topology.
2. Open the Servers summary panel and right click on the device
3. No context menu is being displayed. (works fine in version 2.2.x)
4. Exception is generated in the log file shown below.

![gns3_popup_menu](https://github.com/GNS3/gns3-gui/assets/7124193/76b8737b-8b3c-4f69-84c0-5a7659520539)

```
***** Exception detected, traceback information saved in /home/cioby/.config/GNS3/3.0/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gns3/compute_summary_view.py", line 143, in contextMenuEvent
    self._showContextualMenu(event.globalPos())
  File "/usr/lib/python3.11/site-packages/gns3/compute_summary_view.py", line 149, in _showContextualMenu
    compute = item.getCompute()
              ^^^^^^^^^^^^^^^
AttributeError: 'QTreeWidgetItem' object has no attribute 'getCompute'
```

**Comment by grossmj** [comment]
Fixed, thank you! :)
