### ISSUE TITLE
Fail update installation: No module named 'sip'

### ISSUE THREAD

**Issue by jJit0** [GNS3/gns3-gui#2733]
I get this error when I launch gns3 from CLI or GUI:

`Fail update installation: No module named 'sip'`
`Can't import Qt modules: Qt and/or PyQt is probably not installed correctly...`

It's the version 2.1.14 I have on my debian PC

**Comment by jJit0** [comment]
I already have
`apt install python3-pyqt5 python-pyqt5`
`python3-pyqt5 is already the newest version (5.11.3+dfsg-1+b3)`
`python-pyqt5 is already the newest version (5.11.3+dfsg-1+b3)`

When I activate GNS3-GUI virtualenv and install pyqt5 from pip, I get this error
`source /usr/share/gns3/gns3-gui/bin/activate`
`pip install -U PyQt5 PyQt5-sip`
`Traceback (most recent call last):
  File "/usr/share/gns3/gns3-gui/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/share/gns3/gns3-gui/lib/python3.6/site-packages/pip/__init__.py", line 29, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/share/gns3/gns3-gui/lib/python3.6/site-packages/pip/utils/__init__.py", line 23, in <module>
    from pip.locations import (
  File "/usr/share/gns3/gns3-gui/lib/python3.6/site-packages/pip/locations.py", line 9, in <module>
    from distutils import sysconfig
  File "/usr/share/gns3/gns3-gui/lib/python3.6/distutils/__init__.py", line 25, in <module>
    from distutils import dist, sysconfig
ImportError: cannot import name 'dist'
`
By this error, I shall install python3-distutils, but it's already installed, but with python3.7
`apt install python3-distutils`
`python3-distutils is already the newest version (3.7.2-3)`

I think it's due to python3 version mismatch between my global package and GNS3 virtualenv, but I can't really do anything since my I got python3 updates automatically.

**Comment by grossmj** [comment]
Maybe create a virtual environment using something like this `python3.7 -m venv <myenvname>`

**Comment by jJit0** [comment]
It's what I did
`virtualenv -p python3.7 /home/toor/GNS3`
`pip3 install -U gns3-gui gns3-server PyQt5-sip`

And it fully worked.

This is a temporary solution, I can't work definitely with my created virtualenv.

You need to fix GNS3 and use it with python3.7 in a future update.

**Comment by grossmj** [comment]
Thanks for the feedback. Version 2.2 will officially support Python 3.7

**Comment by EchedeyLR** [comment]
Version 2.2 and the same issue maintained on my case at least.

**Comment by cb4292** [comment]
Working on latest version, 2.2.19. Also still having the same issue. Python version 3.7.3.

**Comment by cb4292** [comment]
> Working on latest version, 2.2.19. Also still having the same issue. Python version 3.7.3.

Finally got gns3 working on Ubuntu 20.04.2 Focal. If anyone is having an issue with Pyqt, or with the gns3-gui version not matching the gns3-server version, this may be a fix.

`sudo apt autoremove gns3-gui`
`sudo apt autoremove gns3-server`

Now, double check that gns3 is actually removed. Go to /usr/local/bin and remove gns3server, gns3loopback, and gns3vmnet.

Credit for the next, obvious step goes to this video:
https://www.youtube.com/watch?v=AaUxYe6FzhA

Go to the PPA http://ppa.launchpad.net/gns3/ppa/ubuntu/pool/main/g/, and download the latest **matching** versions of gns3-server and gns3-gui. Make sure this also matches your Ubuntu release, so in my case I downloaded gns3-gui_2.2.19~focal1_amd64.deb and gns3-server_2.2.19~focal1_amd64.deb.

Next, use `sudo dpkg -i ` to install each of these. In my case, I found I had unmet dependencies. After resolving them with `sudo apt  --fix-broken install`, I got both the gui and the server to install properly. GNS3 then successfully started, and the server matched the gui. 

I know this probably is not a GNS3 issue, and may be some kind of package management issue. Either way, I hope this helps someone who wants to use this great application.

**Comment by jJit0** [comment]
It also works with pipx:

`pipx install gns3-gui`
`pipx inject gns3-gui gns3-server PyQt5`

**Comment by albert-a** [comment]
You can still install the libraries system wide
```
apt install python3-pyqt5.QtSvg python3-pyqt5.qtwebsockets
```
and let the gns3 installation use them with pipx option `--system-site-packages`:
```
pipx install --system-site-packages gns3-gui
```
